import "./styles.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import { SiteHeader } from "../components/site-header";
import { getBaseUrl } from "../lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const baseUrl = getBaseUrl();
  const response = await fetch(`${baseUrl}/api`, { cache: "no-cache" });
  const { avatars } = await response.json();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers avatars={avatars}>
          <SiteHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}
